# Generated by Django 5.1.7 on 2025-06-05 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_address_alter_user_birthday_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='usertype',
            new_name='position',
        ),
    ]
